Instalar dependencias

In [1]:
install.packages('foreign')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Leer el csv

In [2]:
library(readr)
datos<-read.csv('/content/sample_data/evaluaciones_universitarias.csv')

Visualizar el csv

In [3]:
View(datos)

     student_id gender    age career               subject      semester
1    39816      Masculino 23  Economía             Biología     2024-I
2    57301      Masculino 18  Economía             Física       2024-II
3    33519      Femenino  17  Educación            Programación 2024-I
4    49618      Masculino 27  Economía             Programación 2024-II
5    11854      Masculino 30  Ingeniería           Química      2024-I
6    80010      Femenino  20  Ingeniería           Química      2024-II
7    26591      Femenino  29  Ingeniería           Física       2024-I
8    45954      Femenino  28  Arquitectura         Programación 2024-I
9    15965      Femenino  33  Arquitectura         Física       2024-II
10   17146      Masculino 22  Arquitectura         Programación 2024-II
11   82529      Masculino 26  Ciencias de la Salud Estadística  2025-I
12   48290      Masculino 19  Educación            Programación 2025-I
13   26551      Femenino  30  Arquitectura         Programación 2024-II
14   93606      Masculino 19  Arquitectura         Estadística  2024-I
15   74340      Femenino  27  Arquitectura         Biología     2025-I
16   23446      Femenino  23  Ciencias de la Salud Matemáticas  2024-I
17   11607      Masculino 32  Ingeniería           Física       2024-I
18   85243      Femenino  27  Educación            Biología     2024-I
19   47268      Femenino  26  Arquitectura         Física       2025-I
20   71524      Femenino  21  Economía             Biología     2024-II
21   72746      Femenino  28  Ciencias de la Salud Matemáticas  2024-II
22   67733      Masculino 29  Educación            Estadística  2025-I
23   54657      Femenino  27  Ingeniería           Física       2024-II
24   34164      Femenino  29  Ingeniería           Programación 2025-I
25   16734      Femenino  31  Economía             Estadística  2024-II
26   43092      Femenino  17  Arquitectura         Programación 2024-I
27   72616      Masculino 18  Economía             Programación 2025-I
28   24953      Masculino 17  Educación            Programación 2024-II
29   18564      Femenino  33  Ingeniería           Programación 2024-II
30   62521      Masculino 25  Ingeniería           Estadística  2024-II
⋮    ⋮          ⋮         ⋮   ⋮                    ⋮            ⋮
1171 52101      Femenino  22  Ciencias de la Salud Programación 2024-II
1172 23447      Femenino  25  Economía             Química      2024-II
1173 20494      Masculino 18  Arquitectura         Química      2024-I
1174 52981      Masculino 32  Ingeniería           Estadística  2024-I
1175 96628      Masculino 31  Educación            Matemáticas  2024-II
1176 48750      Masculino 22  Arquitectura         Estadística  2024-II
1177 50173      Masculino 31  Ciencias de la Salud Biología     2025-I
1178 68447      Masculino 17  Economía             Programación 2024-II
1179 88986      Masculino 27  Ciencias de la Salud Programación 2025-I
1180 65851      Masculino 23  Arquitectura         Química      2025-I
1181 31842      Masculino 25  Arquitectura         Biología     2024-II
1182 68183      Femenino  24  Educación            Matemáticas  2024-II
1183 56077      Masculino 32  Ciencias de la Salud Biología     2024-II
1184 68606      Femenino  25  Ingeniería           Física       2024-I
1185 15551      Femenino  33  Arquitectura         Química      2024-II
1186 56210      Masculino 24  Arquitectura         Física       2024-I
1187 90589      Masculino 31  Ciencias de la Salud Estadística  2024-I
1188 67008      Masculino 19  Economía             Física       2025-I
1189 45986      Femenino  22  Ingeniería           Física       2024-I
1190 93816      Femenino  35  Arquitectura         Estadística  2024-I
1191 17518      Masculino 23  Arquitectura         Estadística  2024-I
1192 19835      Masculino 20  Educación            Estadística  2025-I
1193 97973      Masculino 19  Economía             Química      2024-I
1194 93560      Femenino  18  Educación            Programación 2024-I
1195 63242      Femenino  22  Educación            Física       2024-II
1196 57619      Femenino  31  Economía             Estadística  2025-I
1197 77251      Femenino  25  Ingeniería           Estadística  2024-II
1198 99051      Masculino 24  Ciencias de la Salud Química      2025-I
1199 30969      Masculino 35  Ingeniería           Química      2024-I
1200 14081      Femenino  18  Ciencias de la Salud Química      2025-I
     exam_score homework_avg attendance_rate final_grade passed
1    45.0       70.2         93.5            76.2        1
2    58.7       66.9         66.0            66.1        1
3    85.3       89.7         81.8            65.7        1
4    70.9       92.9         99.7            54.1        0
5    85.4       58.1         89.9            58.3        0
6    50.2       90.2         79.5            87.4        1
7    66.1       64.7         96.9            83.8        1
8    48.5       76.2         68.2            80.7        1
9    67.8       96.8         97.1            86.0        1
10   40.6       70.8         66.0            53.4        0
11   45.6       72.9         63.8            81.2        1
12   93.0       67.2         60.6            59.6        0
13   62.0       88.3         97.4            78.1        1
14   83.8       64.0         70.5            55.1        0
15   56.6       90.4         94.9            83.4        1
16   99.3       54.6         92.1            57.3        0
17   93.8       52.6         80.5            72.0        1
18   54.4       69.7         91.0            85.3        1
19   44.7       80.3         68.6            58.3        0
20   69.4       89.4         87.4            77.9        1
21   91.3       88.5         73.8            71.2        1
22   99.7       59.8         74.4            59.7        0
23   70.2       50.6         70.9            82.4        1
24   55.2       81.3         98.8            91.2        1
25   85.0       82.4         81.8            55.2        0
26   82.3       58.8         94.0            54.1        0
27   43.7       54.9         81.8            99.2        1
28   93.9       58.5         99.5            86.1        1
29   65.0       83.4         62.5            59.6        0
30   42.7       80.4         87.5            70.5        1
⋮    ⋮          ⋮            ⋮               ⋮           ⋮
1171 41.1       64.8         71.7            87.9        1
1172 48.5       67.9         77.7            51.4        0
1173 61.7       90.3         90.2            74.0        1
1174 69.2       65.3         69.1            50.8        0
1175 70.2       66.2         78.4            59.1        0
1176 55.6       87.6         87.4            70.1        1
1177 90.0       99.9         77.9            71.4        1
1178 81.0       57.2         97.8            93.0        1
1179 98.0       70.0         76.7            56.9        0
1180 70.2       73.8         62.1            94.8        1
1181 75.5       61.7         62.3            66.7        1
1182 87.3       84.4         97.7            80.2        1
1183 84.5       97.8         73.1            92.7        1
1184 80.9       86.9         76.5            52.9        0
1185 82.6       67.2         66.4            92.5        1
1186 90.7       73.8         94.4            87.5        1
1187 82.4       58.8         85.7            74.1        1
1188 93.2       71.3         64.8            74.6        1
1189 77.0       77.2         64.6            63.4        0
1190 62.5       97.0         93.4            97.8        1
1191 41.8       59.0         76.5            98.1        1
1192 63.9       74.8         63.1            71.1        1
1193 95.3       90.3         63.2            96.2        1
1194 96.5       64.6         67.9            59.2        0
1195 74.7       92.6         94.5            72.0        1
1196 40.3       61.1         82.5            87.1        1
1197 76.9       80.6         99.5            66.3        1
1198 49.5       87.9         67.2            93.1        1
1199 60.9       52.4         99.0            78.2        1
1200 65.2       69.8         73.2            58.6        0

In [4]:
head(datos)

  student_id gender    age career     subject      semester exam_score
1 39816      Masculino 23  Economía   Biología     2024-I   45.0
2 57301      Masculino 18  Economía   Física       2024-II  58.7
3 33519      Femenino  17  Educación  Programación 2024-I   85.3
4 49618      Masculino 27  Economía   Programación 2024-II  70.9
5 11854      Masculino 30  Ingeniería Química      2024-I   85.4
6 80010      Femenino  20  Ingeniería Química      2024-II  50.2
  homework_avg attendance_rate final_grade passed
1 70.2         93.5            76.2        1
2 66.9         66.0            66.1        1
3 89.7         81.8            65.7        1
4 92.9         99.7            54.1        0
5 58.1         89.9            58.3        0
6 90.2         79.5            87.4        1

Crear nueva matriz

In [5]:
mi_grupo <- datos[1:5, 1:5]
mi_grupo

  student_id gender    age career     subject
1 39816      Masculino 23  Economía   Biología
2 57301      Masculino 18  Economía   Física
3 33519      Femenino  17  Educación  Programación
4 49618      Masculino 27  Economía   Programación
5 11854      Masculino 30  Ingeniería Química

Agregar nueva variable

In [6]:
datos$NotaEscalada <- datos$final_grade/10

In [7]:
attach(datos)
NotaEscalada

   [1] 7.62 6.61 6.57 5.41 5.83 8.74 8.38 8.07 8.60 5.34 8.12 5.96 7.81 5.51
  [15] 8.34 5.73 7.20 8.53 5.83 7.79 7.12 5.97 8.24 9.12 5.52 5.41 9.92 8.61
  [29] 5.96 7.05 5.43 9.83 6.54 6.58 5.46 5.85 8.41 7.57 5.93 6.61 5.94 7.28
  [43] 7.01 7.97 9.86 7.29 5.92 5.02 8.34 6.64 7.93 8.76 6.92 9.79 6.73 5.06
  [57] 9.01 8.93 7.95 9.34 8.83 8.18 5.63 9.13 9.06 7.00 8.08 8.44 6.36 9.88
  [71] 8.64 5.06 8.49 7.81 8.37 8.82 9.25 8.89 6.82 7.32 8.28 8.09 6.25 7.56
  [85] 9.61 8.02 9.60 9.34 8.03 8.84 9.24 6.05 6.48 5.74 5.79 8.04 6.82 7.62
  [99] 9.73 5.60 9.23 5.34 8.45 8.72 7.39 7.38 9.31 8.77 6.32 8.78 7.16 5.54
 [113] 6.50 5.79 6.14 6.58 7.04 9.16 8.09 7.96 5.28 8.75 6.23 8.93 6.67 9.03
 [127] 7.52 5.46 5.95 6.65 9.45 7.14 9.11 8.01 6.04 5.69 5.25 7.53 7.08 5.04
 [141] 9.24 9.82 8.48 5.79 9.62 8.11 5.23 9.94 5.00 8.58 6.13 8.30 5.66 6.93
 [155] 6.98 7.03 7.57 8.32 5.47 7.18 5.08 6.81 8.09 6.48 8.54 9.11 5.35 7.22
 [169] 7.99 9.89 9.38 9.33 8.62 5.06 8.90 5.21 8.36 7.61 6.46 6.24 6.05 8.70
 [183] 8.20 8.77 7.80 9.38 5.52 8.34 8.24 7.19 6.94 7.70 9.59 9.88 5.32 8.53
 [197] 8.57 6.52 9.31 8.66 5.47 5.48 6.76 7.79 9.00 6.73 5.74 9.67 5.97 8.34
 [211] 7.02 5.45 6.00 5.41 8.93 9.50 9.82 6.07 8.20 8.30 7.99 9.57 7.44 5.57
 [225] 8.40 6.97 5.55 8.08 8.84 6.75 8.14 5.81 5.85 5.29 9.12 8.41 6.43 5.21
 [239] 7.11 5.67 8.92 5.54 8.30 9.92 5.65 8.93 6.02 7.23 5.82 6.41 6.90 9.47
 [253] 6.50 9.74 6.83 5.83 8.28 7.87 6.88 7.76 6.59 9.01 5.35 9.63 5.40 7.35
 [267] 9.39 6.97 6.20 5.30 9.57 7.50 7.05 7.10 9.09 6.69 5.95 5.33 7.08 8.00
 [281] 7.24 9.58 9.83 7.55 9.45 9.24 7.81 5.94 6.88 7.11 6.57 6.61 6.88 6.41
 [295] 5.70 5.41 8.47 5.28 9.77 8.83 7.91 5.76 8.04 8.02 6.03 9.45 6.03 7.98
 [309] 9.73 6.08 9.49 8.96 8.47 5.33 7.88 8.36 7.79 7.72 7.90 7.71 7.33 8.72
 [323] 7.60 7.45 8.75 8.97 9.13 8.40 7.99 8.07 8.99 6.90 8.16 6.55 8.90 7.68
 [337] 9.27 6.00 5.22 8.50 7.19 7.09 9.74 5.81 8.95 8.73 7.93 7.37 5.35 6.24
 [351] 8.90 5.64 5.15 6.40 7.44 8.16 9.54 7.12 6.02 6.03 7.30 9.92 6.39 7.19
 [365] 9.24 7.12 7.15 6.18 7.71 5.62 6.40 6.16 6.90 6.94 5.84 6.15 6.94 7.19
 [379] 8.23 5.46 6.39 5.26 5.98 6.84 6.36 5.66 5.81 8.77 8.75 5.37 7.44 5.70
 [393] 7.00 9.49 7.17 5.34 7.81 8.99 9.42 5.34 5.71 9.77 7.84 7.34 9.90 8.32
 [407] 9.07 5.26 6.24 6.50 7.18 7.43 9.02 8.98 8.49 8.39 7.91 6.46 8.50 5.81
 [421] 9.03 5.29 8.44 8.65 5.24 6.62 5.92 5.70 8.56 5.74 9.75 6.66 6.15 6.15
 [435] 6.19 5.08 9.28 6.64 6.46 6.44 8.79 7.33 9.03 8.45 9.04 5.33 5.18 7.08
 [449] 5.58 5.16 6.50 7.65 5.92 6.32 6.38 9.48 5.47 5.79 8.15 8.41 9.21 7.64
 [463] 9.28 5.96 8.56 9.80 5.73 6.01 7.45 9.17 5.89 6.00 8.91 6.85 7.84 8.07
 [477] 7.77 6.26 6.78 8.79 5.68 9.95 9.59 9.62 7.38 9.96 7.14 7.86 6.05 8.63
 [491] 7.37 5.42 6.33 5.86 5.10 8.47 8.69 5.25 6.66 6.10 8.69 5.06 5.41 9.84
 [505] 6.45 7.38 5.21 8.31 5.75 6.61 8.13 6.78 9.33 9.81 7.64 8.39 5.10 9.80
 [519] 6.77 7.72 8.96 5.54 5.67 6.02 6.97 9.39 7.46 9.78 8.60 8.89 7.36 9.41
 [533] 5.35 7.39 8.03 9.67 5.11 8.47 9.42 8.42 5.26 7.12 9.48 7.75 5.51 5.32
 [547] 9.04 8.90 7.28 6.65 9.77 7.82 5.59 6.14 9.49 8.48 5.73 9.15 5.95 5.74
 [561] 8.76 5.28 9.85 8.15 9.36 9.48 5.70 9.36 6.32 5.45 7.34 6.90 9.88 6.32
 [575] 9.87 5.51 9.58 9.14 7.46 7.72 7.46 6.18 8.29 8.39 5.75 8.77 6.44 6.15
 [589] 8.68 8.76 7.39 8.60 9.58 8.95 5.26 5.19 6.26 5.93 6.11 9.58 9.84 6.85
 [603] 7.45 6.44 7.56 6.67 7.27 9.09 8.10 7.65 7.39 5.81 7.53 7.55 8.94 9.06
 [617] 6.86 9.14 8.17 8.08 9.68 6.83 7.72 5.04 6.31 7.59 6.82 8.09 8.59 8.64
 [631] 6.07 8.20 9.82 8.69 9.33 5.93 8.80 7.79 6.99 8.03 8.61 9.19 7.86 8.64
 [645] 8.75 5.28 8.04 5.59 5.45 5.16 5.19 9.38 7.79 7.98 8.61 7.92 7.75 8.71
 [659] 6.15 5.43 9.73 6.11 9.78 9.99 9.05 7.57 8.82 8.63 8.52 8.56 6.00 7.66
 [673] 7.81 9.61 5.69 6.65 6.26 7.81 5.86 9.56 6.91 7.43 7.58 9.56 7.70 8.15
 [687] 7.56 8.13 5.69 9.86 7.09 5.46 8.35 6.34 5.22 6.67 6.99 7.73 5.76 9.13
 [701] 8.89 5.69 8.12 9.97 5.54 6.61 8.75 5.97 7.42 5.21 7.58 7.73 7.84 5.62
 [715] 9.45 9.16 7.57 8.28 9.99 6.31 5.15 5.65 8.50 5.05 7.26 5.52 6.26 7.41
 [729] 7.22 9.06 9.42 5.24 8.47 5.16 9.35 7.69 8.21 5.85 8.03 9.97 6.15 6.98
 [743] 6.27 6.81 8.21 6.28 8.82 9.20 7.70 7.96 8.23 9.62 9.44 7.54 8.98 5.43
 [757] 9.33 8.76 5.37 9.52 6.12 7.96 7.10 5.80 7.83 5.90 9.72 6.90 7.30 8.74
 [771] 9.17 5.89 9.98 7.43 9.35 8.52 9.32 5.03 6.20 7.41 6.86 9.40 9.05 9.39
 [785] 7.61 6.29 5.71 5.18 5.34 9.36 8.73 9.65 9.54 9.64 5.80 5.21 8.89 7.23
 [799] 6.17 8.92 6.60 9.45 8.52 6.83 6.08 5.16 7.71 8.80 7.04 9.54 9.48 5.97
 [813] 7.29 7.47 5.92 5.48 6.78 5.58 6.67 5.44 9.02 9.92 8.57 8.63 8.43 7.75
 [827] 7.58 5.34 9.81 5.27 9.73 5.66 5.63 5.75 6.22 6.98 6.78 5.45 9.78 5.33
 [841] 7.10 9.21 7.56 6.50 6.12 9.23 7.05 9.25 5.74 7.80 6.18 9.24 6.95 6.34
 [855] 6.97 5.11 7.00 9.27 5.59 7.92 9.05 8.40 6.78 7.78 9.53 5.97 7.22 5.02
 [869] 7.69 5.76 5.60 6.99 8.55 8.92 9.55 5.95 6.11 7.35 9.80 6.77 8.97 5.66
 [883] 8.77 8.59 9.97 9.32 5.52 5.61 5.29 8.65 8.30 6.71 6.06 9.06 7.48 7.15
 [897] 7.37 5.93 7.38 8.49 5.15 9.21 7.40 8.81 5.45 5.12 9.88 5.69 5.90 6.17
 [911] 6.68 6.31 5.61 9.39 7.97 9.09 7.23 6.74 5.19 5.74 8.89 7.91 6.31 5.36
 [925] 8.70 5.54 8.29 6.40 7.33 9.17 7.24 5.05 6.15 9.50 8.75 9.52 9.59 9.05
 [939] 5.26 7.31 9.68 7.20 9.78 5.74 5.93 8.48 8.99 5.89 8.74 5.72 6.91 6.51
 [953] 6.35 5.36 8.17 7.49 6.75 5.75 8.79 5.86 5.14 5.20 5.88 5.56 9.47 9.94
 [967] 7.21 6.41 5.56 5.23 9.40 7.97 7.75 5.01 9.36 7.75 8.30 7.18 8.37 8.16
 [981] 5.54 8.04 8.64 7.03 9.13 5.38 6.76 5.89 8.82 7.83 8.82 8.09 5.02 7.03
 [995] 6.44 9.99 8.31 5.70 7.72 7.70 7.98 9.63 8.80 6.79 9.22 5.10 8.16 9.75
[1009] 7.11 6.62 9.28 8.97 6.86 6.56 9.14 5.34 8.21 7.92 7.51 9.26 6.15 8.66
[1023] 6.00 5.62 8.00 7.78 5.92 6.06 7.12 6.89 5.68 5.14 7.66 6.45 8.10 9.45
[1037] 5.26 8.31 9.49 9.05 5.42 8.88 9.11 7.13 7.52 8.72 9.26 7.87 5.68 7.65
[1051] 8.00 6.61 9.30 5.51 6.20 6.89 5.34 8.17 9.82 5.71 6.35 7.06 8.03 7.55
[1065] 8.74 7.12 6.04 7.56 8.59 5.93 5.34 5.04 6.36 7.41 8.68 9.96 6.07 7.16
[1079] 5.85 7.07 6.69 7.82 8.27 7.55 9.35 5.34 6.13 6.71 5.09 7.10 9.09 5.19
[1093] 9.21 7.07 5.29 7.19 5.43 8.84 6.15 6.12 9.99 6.09 9.97 8.89 9.25 9.16
[1107] 9.21 7.98 7.23 6.30 5.06 9.72 5.27 7.70 6.44 6.31 9.76 8.86 5.88 5.16
[1121] 7.81 9.92 9.73 8.86 5.72 5.44 8.66 7.05 5.92 8.49 9.99 7.89 7.50 5.27
[1135] 9.22 8.45 7.75 7.93 7.10 5.22 5.93 9.12 9.94 8.11 7.37 8.26 6.77 9.11
[1149] 6.69 7.61 9.73 9.17 5.60 9.50 6.76 5.67 8.34 7.21 9.66 5.73 9.07 6.11
[1163] 5.54 6.89 9.34 9.40 7.12 5.56 7.49 8.36 8.79 5.14 7.40 5.08 5.91 7.01
[1177] 7.14 9.30 5.69 9.48 6.67 8.02 9.27 5.29 9.25 8.75 7.41 7.46 6.34 9.78
[1191] 9.81 7.11 9.62 5.92 7.20 8.71 6.63 9.31 7.82 5.86

Informacion adicional del Dataset

In [8]:
str(datos)

'data.frame':	1200 obs. of  12 variables:
 $ student_id     : int  39816 57301 33519 49618 11854 80010 26591 45954 15965 17146 ...
 $ gender         : chr  "Masculino" "Masculino" "Femenino" "Masculino" ...
 $ age            : int  23 18 17 27 30 20 29 28 33 22 ...
 $ career         : chr  "Economía" "Economía" "Educación" "Economía" ...
 $ subject        : chr  "Biología" "Física" "Programación" "Programación" ...
 $ semester       : chr  "2024-I" "2024-II" "2024-I" "2024-II" ...
 $ exam_score     : num  45 58.7 85.3 70.9 85.4 50.2 66.1 48.5 67.8 40.6 ...
 $ homework_avg   : num  70.2 66.9 89.7 92.9 58.1 90.2 64.7 76.2 96.8 70.8 ...
 $ attendance_rate: num  93.5 66 81.8 99.7 89.9 79.5 96.9 68.2 97.1 66 ...
 $ final_grade    : num  76.2 66.1 65.7 54.1 58.3 87.4 83.8 80.7 86 53.4 ...
 $ passed         : int  1 1 1 0 0 1 1 1 1 0 ...
 $ NotaEscalada   : num  7.62 6.61 6.57 5.41 5.83 8.74 8.38 8.07 8.6 5.34 ...

In [9]:
dim(datos)

[1] 1200   12

In [10]:
colnames(datos)

 [1] "student_id"      "gender"          "age"             "career"
 [5] "subject"         "semester"        "exam_score"      "homework_avg"
 [9] "attendance_rate" "final_grade"     "passed"          "NotaEscalada"

In [11]:
names(datos)

 [1] "student_id"      "gender"          "age"             "career"
 [5] "subject"         "semester"        "exam_score"      "homework_avg"
 [9] "attendance_rate" "final_grade"     "passed"          "NotaEscalada"

In [13]:
nrow(datos)

[1] 1200

In [14]:
ncol(datos)

[1] 12

In [15]:
head(datos)

  student_id gender    age career     subject      semester exam_score
1 39816      Masculino 23  Economía   Biología     2024-I   45.0
2 57301      Masculino 18  Economía   Física       2024-II  58.7
3 33519      Femenino  17  Educación  Programación 2024-I   85.3
4 49618      Masculino 27  Economía   Programación 2024-II  70.9
5 11854      Masculino 30  Ingeniería Química      2024-I   85.4
6 80010      Femenino  20  Ingeniería Química      2024-II  50.2
  homework_avg attendance_rate final_grade passed NotaEscalada
1 70.2         93.5            76.2        1      7.62
2 66.9         66.0            66.1        1      6.61
3 89.7         81.8            65.7        1      6.57
4 92.9         99.7            54.1        0      5.41
5 58.1         89.9            58.3        0      5.83
6 90.2         79.5            87.4        1      8.74

In [16]:
tail(datos)

     student_id gender    age career               subject     semester
1195 63242      Femenino  22  Educación            Física      2024-II
1196 57619      Femenino  31  Economía             Estadística 2025-I
1197 77251      Femenino  25  Ingeniería           Estadística 2024-II
1198 99051      Masculino 24  Ciencias de la Salud Química     2025-I
1199 30969      Masculino 35  Ingeniería           Química     2024-I
1200 14081      Femenino  18  Ciencias de la Salud Química     2025-I
     exam_score homework_avg attendance_rate final_grade passed NotaEscalada
1195 74.7       92.6         94.5            72.0        1      7.20
1196 40.3       61.1         82.5            87.1        1      8.71
1197 76.9       80.6         99.5            66.3        1      6.63
1198 49.5       87.9         67.2            93.1        1      9.31
1199 60.9       52.4         99.0            78.2        1      7.82
1200 65.2       69.8         73.2            58.6        0      5.86