In [5]:
import pandas as pd

In [7]:
df = pd.read_csv('./datasets/california_housing_train.csv')

In [9]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [13]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [15]:
print(df.shape)
print(df.size)

(17000, 9)
153000

In [17]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [19]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [21]:
print(df.iloc[1,1])

34.4

In [23]:
print(df.iloc[2,4])

174.0

In [25]:
print(df.iloc[0:5,0:5])

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0    -114.31     34.19                15.0       5612.0          1283.0
1    -114.47     34.40                19.0       7650.0          1901.0
2    -114.56     33.69                17.0        720.0           174.0
3    -114.57     33.64                14.0       1501.0           337.0
4    -114.57     33.57                20.0       1454.0           326.0

In [27]:
print(df.iloc[5:11,0:2])

    longitude  latitude
5     -114.58     33.63
6     -114.58     33.61
7     -114.59     34.83
8     -114.59     33.61
9     -114.60     34.83
10    -114.60     33.62

In [29]:
print(df.iloc[10:26,-3:])

    households  median_income  median_house_value
10       824.0         2.6797             86500.0
11       437.0         1.6250             62000.0
12       211.0         2.1571             48600.0
13       479.0         3.2120             70400.0
14       300.0         0.8585             45000.0
15       401.0         1.6991             69100.0
16       256.0         2.9653             94900.0
17        27.0         0.8571             25000.0
18       320.0         1.2049             44000.0
19        15.0         1.2656             27500.0
20       303.0         1.6395             44400.0
21       139.0         0.8964             59200.0
22        58.0         1.6250             50000.0
23        52.0         3.2097             71300.0
24       283.0         1.6250             53500.0
25        89.0         3.6528            100000.0

In [31]:
print(df.iloc[-10:,2:3])

       housing_median_age
16990                28.0
16991                11.0
16992                52.0
16993                52.0
16994                32.0
16995                52.0
16996                36.0
16997                17.0
16998                19.0
16999                52.0

In [33]:
print(df.iloc[0:10,-4:])

   population  households  median_income  median_house_value
0      1015.0       472.0         1.4936             66900.0
1      1129.0       463.0         1.8200             80100.0
2       333.0       117.0         1.6509             85700.0
3       515.0       226.0         3.1917             73400.0
4       624.0       262.0         1.9250             65500.0
5       671.0       239.0         3.3438             74000.0
6      1841.0       633.0         2.6768             82400.0
7       375.0       158.0         1.7083             48500.0
8      3134.0      1056.0         2.1782             58400.0

In [35]:
print(df.iloc[10:16])

    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
10    -114.60     33.62                16.0       3741.0           801.0
11    -114.60     33.60                21.0       1988.0           483.0
12    -114.61     34.84                48.0       1291.0           248.0
13    -114.61     34.83                31.0       2478.0           464.0
14    -114.63     32.76                15.0       1448.0           378.0
15    -114.65     34.89                17.0       2556.0           587.0

    population  households  median_income  median_house_value
10      2434.0       824.0         2.6797             86500.0
11      1182.0       437.0         1.6250             62000.0
12       580.0       211.0         2.1571             48600.0
13      1346.0       479.0         3.2120             70400.0
14       949.0       300.0         0.8585             45000.0
15      1005.0       401.0         1.6991             69100.0