In [ ]:
#Corpus Español
import nltk
nltk.download("cess_esp")
from nltk.corpus import cess_esp
sentencias = cess_esp.sents()[:300]
sentencias[:2]

[nltk_data] Downloading package cess_esp to /root/nltk_data...
[nltk_data]   Unzipping corpora/cess_esp.zip.

[['El',
  'grupo',
  'estatal',
  'Electricité_de_France',
  '-Fpa-',
  'EDF',
  '-Fpt-',
  'anunció',
  'hoy',
  ',',
  'jueves',
  ',',
  'la',
  'compra',
  'del',
  '51_por_ciento',
  'de',
  'la',
  'empresa',
  'mexicana',
  'Electricidad_Águila_de_Altamira',
  '-Fpa-',
  'EAA',
  '-Fpt-',
  ',',
  'creada',
  'por',
  'el',
  'japonés',
  'Mitsubishi_Corporation',
  'para',
  'poner_en_marcha',
  'una',
  'central',
  'de',
  'gas',
  'de',
  '495',
  'megavatios',
  '.'],
 ['Una',
  'portavoz',
  'de',
  'EDF',
  'explicó',
  'a',
  'EFE',
  'que',
  'el',
  'proyecto',
  'para',
  'la',
  'construcción',
  'de',
  'Altamira_2',
  ',',
  'al',
  'norte',
  'de',
  'Tampico',
  ',',
  'prevé',
  'la',
  'utilización',
  'de',
  'gas',
  'natural',
  'como',
  'combustible',
  'principal',
  'en',
  'una',
  'central',
  'de',
  'ciclo',
  'combinado',
  'que',
  'debe',
  'empezar',
  'a',
  'funcionar',
  'en',
  'mayo_del_2002',
  '.']]

In [ ]:
#Normalizacion basica
import re
def limpiar_tokens(tokens):
  texto = " ".join(tokens).lower()
  texto = re.sub(r"[^a-záéíóúñü\s]", "", texto)
  return texto.split()

tokens_limpios = [limpiar_tokens(s) for s in sentencias]
tokens_limpios[:2]

[['el',
  'grupo',
  'estatal',
  'electricitédefrance',
  'fpa',
  'edf',
  'fpt',
  'anunció',
  'hoy',
  'jueves',
  'la',
  'compra',
  'del',
  'porciento',
  'de',
  'la',
  'empresa',
  'mexicana',
  'electricidadáguiladealtamira',
  'fpa',
  'eaa',
  'fpt',
  'creada',
  'por',
  'el',
  'japonés',
  'mitsubishicorporation',
  'para',
  'ponerenmarcha',
  'una',
  'central',
  'de',
  'gas',
  'de',
  'megavatios'],
 ['una',
  'portavoz',
  'de',
  'edf',
  'explicó',
  'a',
  'efe',
  'que',
  'el',
  'proyecto',
  'para',
  'la',
  'construcción',
  'de',
  'altamira',
  'al',
  'norte',
  'de',
  'tampico',
  'prevé',
  'la',
  'utilización',
  'de',
  'gas',
  'natural',
  'como',
  'combustible',
  'principal',
  'en',
  'una',
  'central',
  'de',
  'ciclo',
  'combinado',
  'que',
  'debe',
  'empezar',
  'a',
  'funcionar',
  'en',
  'mayodel']]

In [ ]:
#Cuenta cuantos tokens tiene cada oracion
longitudes = [len(s) for s in tokens_limpios]
longitudes[:10]

[35, 41, 31, 30, 37, 48, 43, 49, 47, 34]

In [ ]:
#Obtener las palabras mas frecuentes del corpus
from collections import Counter
todas = []
for s in tokens_limpios:
  todas.extend(s)
Counter(todas).most_common(10)

[('de', 604),
 ('la', 458),
 ('el', 407),
 ('que', 301),
 ('en', 288),
 ('y', 269),
 ('los', 196),
 ('a', 185),
 ('del', 163),
 ('las', 116)]

In [ ]:
#Representacion del texto
textos = [" ".join(s) for s in tokens_limpios]
textos[:2]

['el grupo estatal electricitédefrance fpa edf fpt anunció hoy jueves la compra del porciento de la empresa mexicana electricidadáguiladealtamira fpa eaa fpt creada por el japonés mitsubishicorporation para ponerenmarcha una central de gas de megavatios',
 'una portavoz de edf explicó a efe que el proyecto para la construcción de altamira al norte de tampico prevé la utilización de gas natural como combustible principal en una central de ciclo combinado que debe empezar a funcionar en mayodel']

In [ ]:
#BoW
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features=2000)
X_bow = bow.fit_transform(textos)
X_bow.shape

(300, 2000)

In [ ]:
#Convierte la matriz BoW en DataFrame.
import pandas as pd
bow_df = pd.DataFrame(
    X_bow.toarray(),
    columns=bow.get_feature_names_out()
)
bow_df.head()

,abierta,abogado,abogados,abogaron,abogó,abordo,abra,abran,abrazo,abrir,...,éste,éticos,éxito,órgano,última,últimas,últimos,única,únicamente,único
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2000)
X_tfidf = tfidf.fit_transform(textos)

In [ ]:
#Comparar el peso TF-IDF de la palabra "gobierno".
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)
tfidf_df["gobierno"].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: gobierno, dtype: float64

In [ ]:
#Modelos NLP
#Etiquetas
y = [1 if len(s) > 10 else 0 for s in tokens_limpios]

In [ ]:
#Training/Testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.3, random_state=42
)

In [ ]:
#Entrenar Naive Bayes y calcula accuracy.
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
nb = MultinomialNB()
nb.fit(X_train, y_train)
accuracy_score(y_test, nb.predict(X_test))

0.9555555555555556

In [ ]:
#Entrenar Logistic Regression y compara resultados.
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
accuracy_score(y_test, lr.predict(X_test))

0.9555555555555556

In [ ]:
#Preparacion de tokens
tokens_filtrados = [s for s in tokens_limpios if len(s) > 5]

In [ ]:
#Word2Vec
!pip install gensim
from gensim.models import Word2Vec
model = Word2Vec(
    sentences=tokens_filtrados,
    vector_size=100,
    window=5,
    min_count=5
)

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.0)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 38.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
#Buscar palabras similares a "presidente".
model.wv.most_similar("presidente")

[('de', 0.9989535212516785),
 ('a', 0.9988488554954529),
 ('el', 0.9988366961479187),
 ('que', 0.99880051612854),
 ('los', 0.9987949728965759),
 ('en', 0.9987936615943909),
 ('la', 0.9987860321998596),
 ('por', 0.9987683892250061),
 ('las', 0.9987406134605408),
 ('del', 0.998717188835144)]

In [ ]:
#Calcular similitud entre "gobierno" y "estado"
model.wv.similarity("gobierno", "estado")

np.float32(0.9969055)

In [ ]:
#Pipeline
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=3000)),
    ("clf", LogisticRegression(max_iter=1000))
])

In [ ]:
#Training
pipeline.fit(textos, y)

Pipeline(steps=[('tfidf', TfidfVectorizer(max_features=3000)),
                ('clf', LogisticRegression(max_iter=1000))])

In [ ]:
#Predecir la clase del texto:
#"el gobierno aprobo una nueva ley"
pipeline.predict(["el gobierno aprobo una nueva ley"])

array([1])